// <auto-generated />
using System;
using Hinario.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Hinario.Infra.Migrations
{
    [DbContext(typeof(HinarioApiContext))]
    [Migration("20260328022327_AdicionarRepertorio")]
    partial class AdicionarRepertorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hinario.Domain.Models.Hino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identificador")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificador");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("letra");

                    b.Property<NpgsqlTsVector>("LetraIdx")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("letra_idx");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Identificador")
                        .IsUnique()
                        .HasFilter("\"identificador\" IS NOT NULL");

                    b.HasIndex("LetraIdx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LetraIdx"), "GIN");

                    b.ToTable("hinos");
                });

            modelBuilder.Entity("Hinario.Domain.Models.Repertorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("repertorios");
                });

            modelBuilder.Entity("Hinario.Domain.Models.RepertorioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HinoId")
                        .HasColumnType("integer")
                        .HasColumnName("hino_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("RepertorioId")
                        .HasColumnType("integer")
                        .HasColumnName("repertorio_id");

                    b.HasKey("Id");

                    b.HasIndex("HinoId");

                    b.HasIndex("RepertorioId", "Ordem")
                        .IsUnique();

                    b.ToTable("repertorio_itens");
                });

            modelBuilder.Entity("Hinario.Domain.Models.RepertorioItem", b =>
                {
                    b.HasOne("Hinario.Domain.Models.Hino", "Hino")
                        .WithMany()
                        .HasForeignKey("HinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hinario.Domain.Models.Repertorio", "Repertorio")
                        .WithMany("Itens")
                        .HasForeignKey("RepertorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hino");

                    b.Navigation("Repertorio");
                });

            modelBuilder.Entity("Hinario.Domain.Models.Repertorio", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
